global:
  env: testing
# enable visualizer deploy
visualizer:
  enabled: true
  image:
    _default: ghcr.io/blockscout/visualizer:main

  replicas:
    app: 1
  ports:
    http:
      number: 8050
      protocol: TCP
      host: 'http.'
      path: "/"
      pathType: Prefix
    grpc:
      number: 8051
      protocol: TCP
      host: 'grpc.'
      path: "/"
      pathType: Prefix
    metrics:
      number: 6060
      protocol: TCP
      host: "metrics."
      path: "/metrics"
      pathType: Exact

  service:
    # ClusterIP, NodePort or LoadBalancer
    type: ClusterIP

  # enable ingress
  ingress:
    enabled: true
    host:
      _default: visualizer-test.aws-k8s.blockscout.com
    # enable https
    tls:
      enabled: true

  resources:
    limits:
      memory:
        _default: "0.5Gi"
      cpu:
        _default: "0.1"
    requests:
      memory:
        _default: "0.5Gi"
      cpu:
        _default: "0.1"

  # node label
  nodeSelector:
    enabled: true
    app: blockscout

  # probes
  livenessProbe:
    enabled: true
    path: /health
  readinessProbe:
    enabled: true
    path: /health

  # enable Horizontal Pod Autoscaler
  hpa:
    enabled: false
    minReplicas: 1
    maxReplicas: 10
    cpuTarget: 90

  environment:
    VISUALIZER__SERVER__HTTP__ENABLED:
      _default: 'true'
    VISUALIZER__SERVER__HTTP__ADDR:
      _default: 0.0.0.0:8050
    VISUALIZER__SERVER__GRPC__ENABLED:
      _default: 'false'
