[package]
name = "verification"
version = "0.1.0"
# authors = [""]
edition = "2021"
repository = "https://github.com/blockscout/blockscout-rs/verification"

[dependencies]
actix-web = "4"
clap = { version = "3", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
tokio = { version = "0.2", features = ["macros"]}
serde_json = "1"
log = "0.4"
env_logger = "0.9"
thiserror = { version = "1.0" }

ethers-solc = { git = "https://github.com/gakonst/ethers-rs", version = "0.3", features = ["svm-solc"] }