version: "3"
services:
  verification:
    build: .
    ports:
      - "8043:8043"
    environment:
      - VERIFICATION__CONFIG=/app/config.toml
    volumes:
      - ./config/base.toml:/app/config.toml