[server]
addr = "0.0.0.0:8043"

[sourcify]
api_url = "https://sourcify.dev/server/"
verification_attempts = 3
request_timeout = 10

[solidity]

[solidity.fetcher.list]
refresh_versions_schedule = "0 0 * * * * *"
compilers_list_url = "https://solc-bin.ethereum.org/linux-amd64/list.json"

[metrics]
enabled = false
endpoint = "/metrics"
addr = "0.0.0.0:6060"

[jaeger]
enabled = false
agent_endpoint = "localhost:6831"

