[package]
name = "eth-bytecode-db"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
blockscout-display-bytes = { version = "1.0", features = ["ethers-core"] }
bytes = "1.3"
entity = { path = "./entity" }
ethabi = "18.0"
ethers-core = "1.0"
ethers-solc = { version = "1.0", features = ["async"] }
futures = "0.3"
hex = "0.4"
mismatch = "1.0"
sea-orm = { version = "0.10", features = [ "sqlx-postgres", "runtime-tokio-rustls", "macros", "postgres-array", "mock"] }
semver = "1.0"
serde = "1.0"
serde_json = "1.0"
solidity-metadata = "1.0"
thiserror = "1.0"
tokio = {version = "1.21", features = ["full"]}
tracing = "0.1"
tracing-subscriber = {version = "0.3", features = ["env-filter"]}

[dev-dependencies]
pretty_assertions = "1.2"
url = "2.3"
sea-orm-migration = {version = "0.10", features = ["runtime-tokio-rustls", "sqlx-postgres"]}
migration = {path = "./migration"}

