name: docker

on:
  push:
    branches:
      - 'main'
      - 'test-docker'
    tags:
      - '*'

jobs:
  verification:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Format ref
        run: |
          echo ${{github.ref_name}}
          docker_tag=$(echo ${{github.ref_name}} | awk -F "/" '{print $3}')
          echo "DOCKER_TAG=${docker_tag}" >> $GITHUB_ENV
          
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "verification"
          push: true
          tags: ghcr.io/blockscout/verification:${{env.DOCKER_TAG}}